#!/usr/bin/env python3
"""Write the compact, review-only Notebook 04."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

import nbformat as nbf

from notebook_presentation import apply_notebook_presentation


REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = REPO_ROOT / "notebooks" / "04_colocalization_analysis.ipynb"


def _markdown(source: str):
    return nbf.v4.new_markdown_cell(dedent(source).strip())


def _code(source: str):
    return nbf.v4.new_code_cell(dedent(source).strip())


def build_notebook():
    notebook = nbf.v4.new_notebook()
    notebook["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3"},
    }
    notebook["cells"] = [
        _markdown(
            """
            # 04 · Colocalization review

            This notebook is intentionally a thin review layer: it loads tables
            generated by `scripts/build_colocalization_tables.py`, provides
            adjustable filters, and renders directional-first contrast views.
            Statistical
            aggregation, limma contrasts, exact permutations, stability summaries,
            and CSV writing live outside the notebook.
            """
        ),
        _code(
            """
            import sys
            from pathlib import Path

            import pandas as pd
            from IPython.display import display

            REPO_ROOT = Path.cwd().resolve()
            if REPO_ROOT.name == "notebooks":
                REPO_ROOT = REPO_ROOT.parent
            SOURCE_ROOT = str(REPO_ROOT / "src")
            if SOURCE_ROOT not in sys.path:
                sys.path.insert(0, SOURCE_ROOT)

            from spatial_workflow.colocalization import (
                display_contrast_table,
                display_within_condition_colocalization,
                load_colocalization_outputs,
                plot_directional_contrast_overview,
                plot_reciprocal_contrast_overview,
            )
            from spatial_workflow.config import load_config, resolve_path
            from spatial_workflow.review import (
                available_compartments,
                load_review_outputs,
                plot_reciprocal_celltype_overlap,
            )

            CONFIG_PATH = REPO_ROOT / "configs" / "local.yaml"
            config = load_config(CONFIG_PATH)
            results_root = resolve_path(CONFIG_PATH, config["paths"]["results_root"])
            nncomp_output_dir = resolve_path(
                CONFIG_PATH,
                config["nncomp"]["output_dir"],
                root=results_root,
            )
            colocalization_config = config.get("colocalization", {})
            colocalization_output_dir = resolve_path(
                CONFIG_PATH,
                colocalization_config.get(
                    "output_dir", "04_colocalization_analysis"
                ),
                root=results_root,
            )

            nncomp_tables = load_review_outputs(nncomp_output_dir)
            colocalization_tables = load_colocalization_outputs(
                colocalization_output_dir
            )
            celltype_permutation = nncomp_tables.get(
                "within_compartment_celltype_permutation"
            )
            if celltype_permutation is None:
                raise FileNotFoundError(
                    "Run the all-source reciprocal nncomp stage before Notebook 04."
                )
            contrast_results = colocalization_tables["contrast_results"]
            """
        ),
        _markdown(
            """
            ## Review parameters

            Edit this cell and rerun the table or Plotly cells below. The generated
            CSVs are complete tables; these choices only change the displayed view.
            Rebuild the CSVs only when changing `k`, cell-count eligibility, planned
            contrasts, or the upstream permutation artifact:

            ```bash
            python3 \
              scripts/build_colocalization_tables.py \
              --config configs/local.yaml --overwrite
            ```
            """
        ),
        _code(
            """
            review_config = config.get("review", {})
            colocalization_review = colocalization_config.get("review", {})
            domains = available_compartments(
                nncomp_tables["compartment_abundance"]
            )

            # Shared scope and support parameters.
            selected_domain = str(
                review_config.get("selected_domain") or domains[0]
            )
            selected_k = int(
                colocalization_config.get(
                    "k", review_config.get("overlap_k", 2)
                )
            )
            min_cells_a = int(
                colocalization_config.get(
                    "min_cells_a",
                    review_config.get("min_overlap_cells_a", 10),
                )
            )
            min_cells_b = int(
                colocalization_config.get(
                    "min_cells_b",
                    review_config.get("min_overlap_cells_b", 10),
                )
            )
            expected_samples = int(
                colocalization_config.get("expected_samples", 4)
            )

            # Within-condition evidence filters.
            within_min_positive_samples = 3
            within_min_median_delta = 0.0
            within_max_stouffer_q = 0.15
            within_max_partial_q = 0.10

            # Between-condition biological relevance filter. A value of 0.05
            # means at least 5% observed directional overlap in >=1 condition.
            min_observed_colocalization = float(
                colocalization_review.get(
                    "min_observed_colocalization", 0.05
                )
            )
            contrast_plot_top_n = 15
            contrast_plot_max_exact_p = 0.05
            contrast_plot_min_loo_sign_fraction = 1.0
            require_within_condition_colocalization = True
            show_reciprocal_confirmation = True
            show_z_diagnostics = False
            selected_contrast = (
                "vap_igg_vs_naive_igg"
                if "vap_igg_vs_naive_igg" in contrast_results
                else next(iter(contrast_results))
            )

            # Reciprocal Plotly filters.
            plot_cell_types_a = review_config.get("overlap_cell_types_a")
            plot_cell_types_b = review_config.get("overlap_cell_types_b")
            plot_min_samples = int(
                review_config.get("min_overlap_samples", expected_samples)
            )
            plot_min_abs_z_score = float(
                review_config.get("min_abs_z_score", 0.0)
            )
            plot_z_direction = str(review_config.get("z_direction", "both"))

            display(
                pd.Series(
                    {
                        "selected compartment": selected_domain,
                        "k": selected_k,
                        "minimum cells A": min_cells_a,
                        "minimum cells B": min_cells_b,
                        "minimum observed colocalization": (
                            min_observed_colocalization
                        ),
                        "maximum exact permutation p": (
                            contrast_plot_max_exact_p
                        ),
                        "require positive within-condition colocalization": (
                            require_within_condition_colocalization
                        ),
                        "selected contrast": selected_contrast,
                    },
                    name="review parameters",
                ).to_frame()
            )
            """
        ),
        _markdown(
            """
            ## 1. Establish directional colocalization within conditions

            The table combines one-sided sample permutation p-values without
            treating cells as biological replicates. `mean_coefficient` is the
            observed fraction of source cells with the target type among their first
            `k` neighbors; `median_delta` is observed minus permutation-null overlap.
            Direction matters because the source-cell population is the denominator.
            These tests establish colocalization before any between-condition
            difference is interpreted.
            """
        ),
        _code(
            """
            example_directional_within_condition = (
                display_within_condition_colocalization(
                    colocalization_tables,
                    table="directional",
                    compartments=[selected_domain],
                    k_values=[selected_k],
                    min_samples=expected_samples,
                    min_positive_samples=within_min_positive_samples,
                    include_self_pairs=False,
                    min_condition_cells=max(min_cells_a, min_cells_b),
                    min_median_delta=within_min_median_delta,
                    max_stouffer_q=within_max_stouffer_q,
                    max_partial_q=within_max_partial_q,
                    n=50,
                )
            )
            """
        ),
        _markdown(
            """
            ## 2. Primary result: directional changes among colocalized relationships

            A differential result is shown only when the directed relationship
            passes the positive within-condition enrichment criteria above in at
            least one contrast condition. This prevents a statistically different
            pair that is depleted relative to the null in both conditions from
            being described as colocalized.

            Read each aligned row from left to right:

            1. raw prevalence: the observed fraction of source cells neighboring
               the target in each condition;
            2. colocalization: each condition's observed-minus-null mean delta,
               where a filled point marks a condition passing the full enrichment
               gate; and
            3. differential effect: the numerator-minus-denominator change in
               null-adjusted overlap.

            The exact permutation p-value is unadjusted and discrete for a 4-v-4
            design; limma q-values remain available in hover text and detail tables.
            """
        ),
        _code(
            """
            directional_contrast_figures = {}
            for contrast in contrast_results:
                figure = plot_directional_contrast_overview(
                    colocalization_tables,
                    contrast,
                    top_n=contrast_plot_top_n,
                    rank_by="max_abs_contrast",
                    min_observed_colocalization=min_observed_colocalization,
                    require_within_condition_colocalization=(
                        require_within_condition_colocalization
                    ),
                    within_min_positive_samples=within_min_positive_samples,
                    within_min_median_delta=within_min_median_delta,
                    within_max_stouffer_q=within_max_stouffer_q,
                    within_max_partial_q=within_max_partial_q,
                    max_exact_p=contrast_plot_max_exact_p,
                    min_loo_sign_fraction=(
                        contrast_plot_min_loo_sign_fraction
                    ),
                )
                directional_contrast_figures[contrast] = figure
                display(
                    pd.Series(
                        figure.layout.meta,
                        name=f"{contrast}: directional",
                    ).to_frame()
                )
                figure.show()
            """
        ),
        _markdown(
            """
            ### Directional detail table

            This table uses the same colocalization, exact-p, and leave-one-out
            filters as the primary plot. Condition coefficients lead, followed by
            flags showing which condition passes positive colocalization, the
            between-condition effect, and inferential details.
            """
        ),
        _code(
            """
            example_filtered = display_contrast_table(
                colocalization_tables,
                selected_contrast,
                table="directional",
                compartments=None,
                cell_types_a=None,
                min_observed_colocalization=min_observed_colocalization,
                require_within_condition_colocalization=(
                    require_within_condition_colocalization
                ),
                within_min_positive_samples=within_min_positive_samples,
                within_min_median_delta=within_min_median_delta,
                within_max_stouffer_q=within_max_stouffer_q,
                within_max_partial_q=within_max_partial_q,
                max_exact_p=contrast_plot_max_exact_p,
                min_loo_sign_fraction=contrast_plot_min_loo_sign_fraction,
                include_sample_counts=False,
                n=50,
            )
            """
        ),
        _markdown(
            """
            ## 3. Secondary result: reciprocal confirmation

            Reciprocal evidence asks whether the relationship is positively
            colocalized in both directions. It is stricter and is presented after
            the directional result so genuine one-way biology is not discarded.
            The same observed-overlap, within-condition enrichment, exact-p, and
            leave-one-out filters are applied.
            """
        ),
        _code(
            """
            reciprocal_contrast_figures = {}
            if show_reciprocal_confirmation:
                for contrast in contrast_results:
                    figure = plot_reciprocal_contrast_overview(
                        colocalization_tables,
                        contrast,
                        top_n=contrast_plot_top_n,
                        rank_by="max_abs_contrast",
                        reciprocal_same_direction=True,
                        min_observed_colocalization=(
                            min_observed_colocalization
                        ),
                        require_within_condition_colocalization=(
                            require_within_condition_colocalization
                        ),
                        within_min_positive_samples=(
                            within_min_positive_samples
                        ),
                        within_min_median_delta=within_min_median_delta,
                        within_max_stouffer_q=within_max_stouffer_q,
                        within_max_partial_q=within_max_partial_q,
                        max_exact_p=contrast_plot_max_exact_p,
                        min_loo_sign_fraction=(
                            contrast_plot_min_loo_sign_fraction
                        ),
                    )
                    reciprocal_contrast_figures[contrast] = figure
                    display(
                        pd.Series(
                            figure.layout.meta,
                            name=f"{contrast}: reciprocal",
                        ).to_frame()
                    )
                    figure.show()
            else:
                print("Set show_reciprocal_confirmation=True to render this view.")
            """
        ),
        _code(
            """
            reciprocal_detail = display_contrast_table(
                colocalization_tables,
                selected_contrast,
                table="reciprocal",
                reciprocal_same_direction=True,
                min_observed_colocalization=min_observed_colocalization,
                require_within_condition_colocalization=(
                    require_within_condition_colocalization
                ),
                within_min_positive_samples=within_min_positive_samples,
                within_min_median_delta=within_min_median_delta,
                within_max_stouffer_q=within_max_stouffer_q,
                within_max_partial_q=within_max_partial_q,
                max_exact_p=contrast_plot_max_exact_p,
                min_loo_sign_fraction=contrast_plot_min_loo_sign_fraction,
                n=20,
            )
            """
        ),
        _markdown(
            """
            ## 4. Optional diagnostic: reciprocal z-score geometry

            For A→B, the Manders-like observed coefficient is

            `(# A cells with at least one B among their first k neighbors) / (# A cells)`.

            The null keeps the coordinates, compartments, and ranked-neighbor graph
            fixed, then shuffles cell-type labels within each sample × compartment.
            The reported score is

            `z = (observed coefficient - permutation null mean) / permutation null SD`.

            Therefore a negative z-score means **fewer A cells neighbor B than the
            label-shuffle null expects**, conditional on that sample's compartment,
            cell-type abundances, and fixed geometry. For example, `z = -2` means the
            observed fraction is two null standard deviations below its expected
            value. It suggests relative depletion or spatial segregation—not a
            negative overlap fraction, and not proof that A and B never touch.

            The sign is directional: A→B and B→A can differ because their
            denominators are different populations. Use `delta` for the interpretable
            absolute percentage-point departure and `coefficient` for how common the
            observed relationship is. Use `p_depleted`/`q_depleted` for formal
            depletion evidence; `p_enriched`/`q_enriched` test the opposite tail.
            A z-score is undefined when the permutation null SD is zero.
            """
        ),
        _markdown(
            """
            ### Sample-level reciprocal z-score view

            Points show A→B versus B→A permutation z-scores at the sample level and
            as condition means. Hover text carries sample, condition, compartment,
            pair, support counts, and both directional scores. This diagnostic is
            off by default because it is not the primary biological result.
            """
        ),
        _code(
            """
            if not show_z_diagnostics:
                print("Set show_z_diagnostics=True to render the z-score view.")
            """
        ),
        _code(
            """
            if show_z_diagnostics:
                selected_compartment_figure = plot_reciprocal_celltype_overlap(
                    celltype_permutation,
                    compartment=selected_domain,
                    cell_types_a=plot_cell_types_a,
                    cell_types_b=plot_cell_types_b,
                    k_value=selected_k,
                    min_cells_a=min_cells_a,
                    min_cells_b=min_cells_b,
                    min_samples=plot_min_samples,
                    min_abs_z_score=plot_min_abs_z_score,
                    z_direction=plot_z_direction,
                )
                display(
                    pd.Series(
                        selected_compartment_figure.layout.meta,
                        name=f"compartment {selected_domain}",
                    ).to_frame()
                )
                selected_compartment_figure.show()
            """
        ),
    ]
    return apply_notebook_presentation(notebook, "04")


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(build_notebook(), NOTEBOOK_PATH)
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
